version: '3'
services:

  mongo:
    image: mongo
    ports:
    - "27017:27017"
      
  zookeeper:
    image: wurstmeister/zookeeper
 
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
